### ISSUE TITLE
How use customized dataset?

### ISSUE THREAD

**Issue by chiyuzhang94** [andreeaiana/newsreclib#1]
Hi @andreeaiana ,

Thanks for this great work! 

I wonder if I can run models with a customized dataset or not. Any guidance?

Best,
Chiyu

**Comment by andreeaiana** [comment]
Hi @chiyuzhang94,

You can run the implemented models with a customized dataset. For this, you would have to do the following:

- Implement your own data preprocessing class (see [MIND preprocessing](https://github.com/andreeaiana/newsreclib/blob/main/newsreclib/data/components/mind_dataframe.py) for an example).

- The output of the data preprocessing should be in the following format:
_  _news_ should be a _pd.DataFrame_ containing news features as specified as a list of _dataset_attributes_ (see [MIND config file](https://github.com/andreeaiana/newsreclib/blob/main/configs/data/mind_rec.yaml) for an example of supported features)
_ _behaviors_ should be a _pd.DataFrame_ containing the click behavior of users in the format: user (ID), history (list of clicked news IDs), candidates (list of candidate news IDs), labels (binary, for the candidates).

- Create a dedicated config file for your dataset (see [MIND config file](https://github.com/andreeaiana/newsreclib/blob/main/configs/data/mind_rec.yaml) for an example). Most importantly, you need to define which attributes your dataset has, by modifying the _dataset_attributes_ variable (e.g., if you don't have any sentiment scores, remove the value from the list of used attributes).
- If you're planning to use categorical variables (e.g., topical category), this should be encoded during the dataset preprocessing.

Let me know if you have any more questions.

Best,
Andreea

**Comment by chiyuzhang94** [comment]
Hi @andreeaiana ,

Thanks for the explanation. I wonder if you can provide a sample of processed dataset?

**Comment by andreeaiana** [comment]
I sent you an email with samples of the processed dataset.

**Comment by chiyuzhang94** [comment]
Hi @andreeaiana ,

I wonder how you split the development and testing set. Where I can find the code for this?

**Comment by andreeaiana** [comment]
I split the MIND dataset in the [mind_dataframe.py](https://github.com/andreeaiana/newsreclib/blob/main/newsreclib/data/components/mind_dataframe.py) script. 

- If you want to re-use that script, you should set `download = False`, and modified the `_load_behaviors` function where the train/val splits are created.
- If you have a custom dataset with your own preprocessing script, pass the different splits directly to the [mind_rec_datamodule.py](https://github.com/andreeaiana/newsreclib/blob/main/newsreclib/data/mind_rec_datamodule.py)

**Comment by chiyuzhang94** [comment]
Thanks. 

Should I change these lines? [1](https://github.com/andreeaiana/newsreclib/blob/e6dbdd738e33588b3722bb8068e83c9943d396e3/newsreclib/data/mind_rec_datamodule.py#L196), [2](https://github.com/andreeaiana/newsreclib/blob/e6dbdd738e33588b3722bb8068e83c9943d396e3/newsreclib/data/mind_rec_datamodule.py#L170)

`data_dir=to_my_file_path`

**Comment by andreeaiana** [comment]
Yes, you can change the `data_dir=my_file_path` either in the configuration of your datamodule or that of your experiment.
