### ISSUE TITLE
DataSet Can’t Be Downloaded successfully

### ISSUE THREAD

**Issue by yanjinYoungOG** [andreeaiana/newsreclib#25]
hello，I wanna know which direction should I put the in the project? I have some trouble downloading the datasets while running train.py，so I downloaded them by myself. But I have no idea where should they be located? 

.\newsreclib\newsreclib\data

or

.\newsreclib\configs\data

or

somewhere else

**Comment by andreeaiana** [comment]
The datasets should be placed in a new directory with the location `./newsreclib/data`.

**Comment by yanjinYoungOG** [comment]
> The datasets should be placed in a new directory with the location `./newsreclib/data`.

thanks, I got it
